services:
  flask:
    build: .
    environment:
      - SCRIPT_NAME=/api
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - HTTP_PORT=5001
    stop_signal: SIGQUIT

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - flask
