services:
  fastapi:
    build: .
    environment:
      - ROOT_PATH=/api
      - HTTP_PORT=5001
    stop_signal: SIGQUIT

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - fastapi
